global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "jenkins"
    static_configs:
      - targets: ["jenkins:8080"]

  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
